Fixes locale configuration error
The command needs to be run as shell, otherwise it tries to call locale.>> and fails with:

`ERROR: undefined method '>>' for "pt_BR.UTF-8 UTF-8":String`